# This workflow will build docker image and deploy it to Docker Hub.
name: Build and Deploy.
on:
  push:
    branches: ["master"]

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Cloning Calculator repository...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and push to DockerHub...
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
