# This workflow will build docker image and deploy it to Docker Hub.
name: Build and Deploy.
on:
  push:
    branches: ["master"]

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Cloning Calculator repository...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub...
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub...
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ejdecena/test-ci-cd
