# This workflow will build docker image and deploy it to Docker Hub.
name: Build and Deploy.
on:
  push:
    branches: ["master"]

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning Calculator repository...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Hello.
        run: echo "Hello world!"
