# This workflow will install Python dependencies, run tests
# and lint with a single version of Python.
name: Lint and Tests.
on:
  pull_request:
    branches: ["master"]

jobs:
  Lint_and_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setting Python version 3.8...
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Cloning Calculator repository...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing requirements...
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Runing flake8 linter...
        run: flake8 --config=flake8

      - name: Runing tests...
        run: python -m unittest -v tests/*.py
